### ISSUE TITLE
gcov fails for Coveralls on Travis CI?

### ISSUE THREAD

**Issue by cdeterman** [jimhester/covr#176]
I have been using `covr` for a while now with Travis CI but I just noticed that it has been quietly returning an error at the end of my install (haven't been focused on coverage recently).  I keep receiving the following error:

>Error: Command `'/usr/bin/gcov' 'home/travis/build/cdeterman/gpuR/src/context.gcno' '-o' '/home/travis/build/cdeterman/gpuR/src'` failed (1)

You can see the most recent build [here](https://travis-ci.org/cdeterman/gpuR/builds/128383295).  Any insight would be appreciated.

**Comment by jimhester** [comment]
You are using gcc-4.8 to compile the code, so you need to use gcov-4.8 to compute the coverage. Changing your travis to the following should fix the issue.

```r
after_success:
  - Rscript -e 'options(covr.gcov = "gcov-4.8");library(covr);coveralls()'
```

**Comment by cdeterman** [comment]
That did in fact fix the problem, thank you.

**Comment by cdeterman** [comment]
I actually have run in to this issue again.  I am using gcc-4.8 to compile and I am setting to use gcov-4.8 for covr options.   Yet I still get the same compilation from the end of the [build](https://travis-ci.org/gpuRcore/gpuRclblas/builds/154250676).  I feel like I must be missing something simple here.  Thoughts?

**Comment by jimhester** [comment]
You are never setting CXX in either your personal nor package makefiles, so the package shared library is not using gcc-4.8. This can be seen when installing your dependencies (i.e. https://travis-ci.org/gpuRcore/gpuRclblas/builds/154250676#L6049)

**Comment by cdeterman** [comment]
Isn't that what I did on line 726 in that link?

```export CXX="g++-4.8"```

**Comment by jimhester** [comment]
No. R does not use system environment variables when compiling packages, you need to use a Makevars file. See [Customizing package compilation](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Customizing-package-compilation)
