### ISSUE TITLE
Latest few diffs break covr package

### ISSUE THREAD

**Issue by FrankPortman** [jimhester/covr#272]
Apologies for semi-vague description but I figured you'd want to look into this ASAP.

A contributor landed a PR on my package the other day which dropped code coverage on my project by ~5%. Upon inspection of the diff, it did not seem obvious why this happening. In fact, certain lines that are run procedurally had random gaps in coverage (this should be impossible). 

Upon reverting to the CRAN version of covr this seems to fix itself.

Consider these 2 examples. The only diff in the former is using the CRAN version of covr rather than Github version.

[Using CRAN](https://codecov.io/gh/FrankPortman/bayesAB/src/b0cbc1406b7a2879357953d4c570acb7d326c3b3/R/generics.R)

[Using Github](https://codecov.io/gh/FrankPortman/bayesAB/src/d908f3f8cd702af31e182664f4b53dbf558f815f/R/generics.R)

**Comment by jimhester** [comment]
Thanks, should now be fixed.

Note previously if statements without braces were not tracked, due to a bug in the way R assigns source references. They now are tracked, so in your example there are a couple lines now uncovered because the bodies are never executed in your tests.

**Comment by Enchufa2** [comment]
I'm afraid that it's not fixed yet. The coverage dropped by ~5% (basically, [the R dir is not covered at all](https://codecov.io/gh/r-simmer/simmer/branch/master)), and nothing changed with the latest commit (ee50a22).

**Comment by jimhester** [comment]
@Enchufa2 Now working as of https://github.com/jimhester/covr/commit/4e6da571cb064ba7310c0db1f999acd13fd87f45
