### ISSUE TITLE
Coverage not supported for error tests?

### ISSUE THREAD

**Issue by zkamvar** [jimhester/covr#88]
In my package, I have [a few tests for errors](https://github.com/grunwaldlab/poppr/blob/2.0-rc/tests/testthat/test-errors.R). When I attempt to run `package_coverage(quiet = FALSE)`, I see that it encounters these errors and then stops doing whatever it's doing and leaves temporary files in my directory.

These are the temporary files:

	src/bitwise_distance.gcda
	src/bitwise_distance.gcno
	src/mlg_clustering.gcda
	src/mlg_clustering.gcno
	src/msn.gcda
	src/msn.gcno
	src/omp_test.gcda
	src/omp_test.gcno
	src/permut_shuffler.gcda
	src/permut_shuffler.gcno
	src/poppr_distance.gcda
	src/poppr_distance.gcno
	tests/testthat/last.dump.rda

Is it choking on the errors?

For reference, this is the version at which I tested my package:
https://github.com/grunwaldlab/poppr/tree/08ef078d17dac10d1e0c96f929b49fbe46cb0c43

**Comment by jimhester** [comment]
This is happening because covr sets `options(error)` on the subprocess, see [R/subprocess.R#L33](https://github.com/jimhester/covr/blob/0b941895b158a703dddec76c42c3fab9aba48f30/R/subprocess.R#L33).  I will try and figure out a way to handle it.

**Comment by jimhester** [comment]
This should now be fixed in the [expect_error](https://github.com/jimhester/covr/tree/expect_error) branch. It can be installed by

```r
devtools::install_github("jimhester/covr@expect_error")
```

Could you confirm that it fixes the issue on your machine (It does so on mine).  If so I will merge it and close this issue.

**Comment by zkamvar** [comment]
Thanks for the quick fix! 

Indeed it works with one note: I still get `last.dump.rda` in my testthat directory.

**Comment by jimhester** [comment]
Looking into this a little more this is actually caused by a something weird going on with `poppr`'s environment.  The `expect_error()` functions work like expected as long as the execution environment is from a package other than `poppr`.

If I have an `test-error.R` file like 

```r
context("hi")
test_that("error", {
  f1 <- function() { stop("hi") }
  expect_error(f1())
  expect_error(stop("hi2"))
})
```

Running the following on 0b941895b158a703dddec76c42c3fab9aba48f30 generates an uncaught error (and corresponding last.dump.rda file)

```r
covr:::subprocess({library(testthat);sys.source("test-error.R", env = new.env(parent=getNamespace("poppr")))})
```

However doing the same with other packages (which load the testthat environment) does _not_ generate an uncaught error.
```r
covr:::subprocess({library(testthat);sys.source("test-error.R", env = new.env(parent=getNamespace("covr")))})

covr:::subprocess({library(testthat);sys.source("test-error.R", env = new.env(parent=getNamespace("testthat")))})

# S4 package
covr:::subprocess({library(testthat);sys.source("test-error.R", env = new.env(parent=getNamespace("tuneR")))})
```

I honestly have no clue what is going on, but I will continue to investigate it.  If you have any ideas I would love to hear them.

**Comment by zkamvar** [comment]
I'm not getting this issue. I placed `test-error.R` in my Downloads directory and ran your commands in R:

```r
09:42:03~/Downloads> R

R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> covr:::subprocess({library(testthat);sys.source("test-error.R", env = new.env(parent=getNamespace("covr")))})
file64557d96ac2.Rout does not exist1
/var/folders/qd/dpdhfsz12wb3c7wz0xdm6dbm0000gn/T//RtmpTXxwor/file6457b543e97 does not exist2
>
> covr:::subprocess({library(testthat);sys.source("test-error.R", env = new.env(parent=getNamespace("testthat")))})
file6452da88468.Rout does not exist1
/var/folders/qd/dpdhfsz12wb3c7wz0xdm6dbm0000gn/T//RtmpTXxwor/file645322161fe does not exist2
> covr:::subprocess({library(testthat);sys.source("test-error.R", env = new.env(parent=getNamespace("poppr")))})
file6453674d71f.Rout does not exist1
/var/folders/qd/dpdhfsz12wb3c7wz0xdm6dbm0000gn/T//RtmpTXxwor/file645265389b1 does not exist2
> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value
 version  R version 3.2.0 (2015-04-16)
 system   x86_64, darwin13.4.0
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       America/Los_Angeles

Packages -----------------------------------------------------------------------
 package    * version date       source
 covr       * 1.0.0   2015-05-21 Github (jimhester/covr@0b94189)
 devtools   * 1.7.0   2015-01-17 CRAN (R 3.2.0)
 lazyeval   * 0.1.10  2015-01-02 CRAN (R 3.1.2)
 magrittr   * 1.5     2014-11-22 CRAN (R 3.2.0)
 rex        * 0.2.0   2014-11-26 CRAN (R 3.1.2)
 rstudioapi * 0.3.1   2015-04-07 CRAN (R 3.2.0)
```

However, `*.gcda` files are building up in my poppr `src/` directory as a result. 


## Modifying `poppr/tests/testthat/test-errors.R`

I attempted to comment out the tests in `test-errors.R` and I got this output:

```
file6a4698208b9.Rout does not exist1
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
```

Note that all files were cleaned up and all of the coverage tests had completed.
I then attempted to simply add one error test independent of the package:

```r
context("Errors and Exceptions")

test_that("bruvo.msn throws errors with incorrect add and loss arguments", {
    expect_error(stop("hammertime"))
#  data("partial_clone", package = "poppr")
#  reps <- rep(1, 10)
#  expect_error(bruvo.msn(partial_clone[1:10], replen = reps, add = "1", loss = TRUE))
#  expect_error(bruvo.msn(partial_clone[1:10], replen = reps, add = TRUE, loss = "TRUE"))
#  expect_error(bruvo.msn(partial_clone[1:10], replen = reps, add = matrix(TRUE, 10, 10), loss = TRUE))
})
```

It cleaned up well and the tests completed, but I got the same messages:

```
file6a4307472df.Rout does not exist1
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
Unexpected version: *904.
Invalid .gcno File!
```

I don't know if any of this helps.

**Comment by jimhester** [comment]
Still trying to track this down, this works fine for many S4 packages that use `expect_error()`.  I did find the same error with https://github.com/Bioconductor-mirror/GenomicTuples, so I am going to try and figure out what the common denominator is.

**Comment by zkamvar** [comment]
An interesting thing to note:

Any time I use `library("poppr")`, even after restarting R, `*.gcda` files are generated in my `src/` directory.

**Comment by jimhester** [comment]
The gcda files are generated because the package code was compiled with
compiler flags to enable test coverage using [gcov](
https://gcc.gnu.org/onlinedocs/gcc/Gcov.html).  If you recompile the
package code normally this behavior will go away.  It is also unrelated to
the issue with the try calls being ignored.
